//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Engine.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    public sealed partial class SystemSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static SystemSettings defaultInstance = ((SystemSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SystemSettings())));
        
        public static SystemSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1920, 1080")]
        public global::System.Drawing.Size Video_Resolution {
            get {
                return ((global::System.Drawing.Size)(this["Video_Resolution"]));
            }
            set {
                this["Video_Resolution"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point Video_Location {
            get {
                return ((global::System.Drawing.Point)(this["Video_Location"]));
            }
            set {
                this["Video_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Video_IsFullscreen {
            get {
                return ((bool)(this["Video_IsFullscreen"]));
            }
            set {
                this["Video_IsFullscreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Video_Monitor {
            get {
                return ((string)(this["Video_Monitor"]));
            }
            set {
                this["Video_Monitor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int Audio_MasterVolume {
            get {
                return ((int)(this["Audio_MasterVolume"]));
            }
            set {
                this["Audio_MasterVolume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int Audio_EffectsVolume {
            get {
                return ((int)(this["Audio_EffectsVolume"]));
            }
            set {
                this["Audio_EffectsVolume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int Audio_MusicVolume {
            get {
                return ((int)(this["Audio_MusicVolume"]));
            }
            set {
                this["Audio_MusicVolume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Audio_Enabled {
            get {
                return ((bool)(this["Audio_Enabled"]));
            }
            set {
                this["Audio_Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color Video_BackgroundColor {
            get {
                return ((global::System.Drawing.Color)(this["Video_BackgroundColor"]));
            }
            set {
                this["Video_BackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Video_IsBorderless {
            get {
                return ((bool)(this["Video_IsBorderless"]));
            }
            set {
                this["Video_IsBorderless"] = value;
            }
        }
    }
}
